### ISSUE TITLE
The txt files aren't diffs?

### ISSUE THREAD

**Issue by rbrown** [gravitydepartment/magento-release-diffs#1]
Hello, all the txt files are generated with --name-status, but the way the README makes it sound like you should be producing patchable diffs?

> --name-status
> Show only names and status of changed files. See the description of the --diff-filter option on what the status letters mean.

**Comment by brendanfalkowski** [comment]
Good question. I use the `--name-status` option because it suits is my workflow.

## Why not patchable diffs

I'm not against providing patchable `.diff` files in this repo, but they're not really useful to me because:

1. They're verbose, and too difficult to read (for people).
1. If you wanted to apply patch files, you would do that without stripping the copyright info. Making patches without the copyright info wouldn't really help anyone.
1. Patches are really only useful if the code you're patching isn't customized. For me, it's always heavily customized (frontend work) so I couldn't apply a patch if I wanted to.

## Why simple diffs

Using `--name-status` has these advantages for me:

1. One filename per line is readable, and easy to scan (for people).
1. Change type is obvious: `a` added, `m` modified, `d` deleted

The simplified diff helps quickly assess if a release impacts files you've customized for a project without getting bogged down in the actual changes. You can then use a feature-rich app for inspecting the diff, which is 1000x better than reading a patch.

FYI — I use these apps when integrating core changes into customizations:

- https://www.git-tower.com/mac/
- https://www.kaleidoscopeapp.com/
